Repository apache/hop, pull requests merged in 2023-11, with the labels that each got.

#3329 Brazilian portuguese translation of hopgui
  ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_pt_BR.properties
Labels: Hop Gui

#3259 Update variables.adoc to add more info on fields, parameters, and vars
  docs/hop-user-manual/modules/ROOT/pages/variables.adoc
Labels: Documentation

#3351 Update filterrows.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/filterrows.adoc
Labels: Documentation

#3340 Update replacestring.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/replacestring.adoc
Labels: Documentation

#3341 Update loops-in-apache-hop.adoc
  docs/hop-user-manual/modules/ROOT/pages/how-to-guides/loops-in-apache-hop.adoc
Labels: Documentation

#3342 Update getvariable.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc
Labels: Documentation

#3343 Update jsoninput.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/jsoninput.adoc
Labels: Documentation

#3344 Update simple-mapping.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/simple-mapping.adoc
Labels: Documentation

#3345 Update filterrows.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/filterrows.adoc
Labels: Documentation

#3346 Update rest.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/rest.adoc
Labels: Documentation

#3350 Update javascript.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/javascript.adoc
Labels: Documentation

#3352 Update HopGuiKeyHandler.java
  plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/ScriptDialog.java
  ui/src/main/java/org/apache/hop/ui/hopgui/HopGuiKeyHandler.java
Labels: Hop Gui

#3359 Update coalesce.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/coalesce.adoc
Labels: Documentation

#3358 Update filterrows.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/filterrows.adoc
Labels: Documentation

#3362 Remote Work Configurations Won't Work Because of Turkish Characters #3356
  engine/src/main/java/org/apache/hop/server/HopServer.java
  engine/src/main/java/org/apache/hop/www/RegisterPipelineServlet.java
  engine/src/main/java/org/apache/hop/www/RegisterWorkflowServlet.java
Labels: Hop Server

#3366 Fix some translations Configuration perspective > Plugins #3220
  plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/config/AzureConfigPlugin.java
  plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/config/messages/messages_en_US.properties
  plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/config/GoogleCloudConfigPlugin.java
  plugins/tech/google/src/main/resources/org/apache/hop/vfs/gs/config/messages/messages_en_US.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/explorer/config/messages/messages_en_US.properties
Labels: Translations

#3370 Fixes #3369 Update userdefinedjavaexpression.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/userdefinedjavaexpression.adoc
Labels: Documentation

#3371 Fixes #3369 Update installation-configuration.adoc
  docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc
Labels: Documentation

#3384 Update setvariable.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/setvariable.adoc
Labels: Documentation

#3383 Update tableoutput.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/tableoutput.adoc
Labels: Documentation

#3382 Update tableinput.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/tableinput.adoc
Labels: Documentation

#3381 Update filterrows.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/filterrows.adoc
Labels: Documentation

#3380 Update getrowsfromresult.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getrowsfromresult.adoc
Labels: Documentation

#3379 Update pipeline-executor.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/pipeline-executor.adoc
Labels: Documentation

#3378 Update simple-mapping.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/simple-mapping.adoc
Labels: Documentation

#3377 Update repeat.adoc
  docs/hop-user-manual/modules/ROOT/pages/workflow/actions/repeat.adoc
Labels: Documentation

#3376 Update pipeline.adoc
  docs/hop-user-manual/modules/ROOT/pages/workflow/actions/pipeline.adoc
Labels: Documentation

#3375 Update copyrowstoresult.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/copyrowstoresult.adoc
Labels: Documentation

#3374 Update getvariable.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc
Labels: Documentation

#3289 [Feature] Feature/3287 - Enable Generating Arrays Inside JSON for Grouped Values
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/enhancedjsonoutput.adoc
  integration-tests/transforms/0068-enhanced-json-output-grouping-unit-testing.hpl
  integration-tests/transforms/0068-enhanced-json-output-grouping.hpl
  integration-tests/transforms/datasets/golden-json-grouped-output.csv
  integration-tests/transforms/datasets/golden-json-grouped-single-item-output.csv
  integration-tests/transforms/datasets/input-enhanced-json-test.csv
  integration-tests/transforms/main-0068-enhanced-json-2927.hwf
  integration-tests/transforms/metadata/dataset/golden-json-grouped-output.json
  integration-tests/transforms/metadata/dataset/golden-json-grouped-single-item-output.json
  integration-tests/transforms/metadata/dataset/input-enhanced-json-test.csv.json
  integration-tests/transforms/metadata/unit-test/0068-enhanced-json-grouping-test.json
  plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutput.java
  plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutputDialog.java
  plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutputField.java
  plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutputenhanced/JsonOutputMeta.java
  plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsonoutputenhanced/messages/messages_en_US.properties
Labels: Documentation, Integration Testing

#3390 [DOC] update the jdbc references
  assemblies/lib-jdbc/pom.xml
  assemblies/plugins/actions/snowflake/pom.xml
  assemblies/plugins/transforms/snowflake/pom.xml
  docs/hop-user-manual/modules/ROOT/pages/database/databases/access.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/as400.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/cache.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/clickhouse.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/db2.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/derby.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/doris.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/duckdb.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/exasol.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/firebird.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/googlebigquery.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/greenplum.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/h2.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/hypersonic.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/infobright.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/informix.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/ingres.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/interbase.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/iris.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/kingbasees.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/mariadb.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/monetdb.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/mssql.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/mssqlnative.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/mysql.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/netezza.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/oracle.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/oraclerdb.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/postgresql.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/redshift.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/sapdb.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/snowflake.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/sqlbase.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/sqlite.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/sybase.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/sybaseiq.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/teradata.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/universe.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/vectorwise.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/vertica.adoc
  plugins/transforms/snowflake/pom.xml
Labels: Documentation

#3394 fix #3189
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/concatfields.adoc
Labels: Documentation

#3393 issues #3324, #3247, #3309, #3231
  docs/hop-user-manual/modules/ROOT/pages/password/passwords/aespasswords.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/snowflakebulkloader.adoc
  plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/ScriptDialog.java
  plugins/transforms/script/src/main/resources/org/apache/hop/pipeline/transforms/script/messages/messages_en_US.properties
  plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoader.java
  ui/src/main/java/org/apache/hop/ui/core/dialog/HopDescribedVariablesDialog.java
  ui/src/main/java/org/apache/hop/ui/core/widget/TableView.java
  ui/src/main/resources/org/apache/hop/ui/core/dialog/messages/messages_en_US.properties
Labels: Documentation, Hop Gui

#3402 Update javascript.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/javascript.adoc
Labels: Documentation

#3415 Update javascript.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/javascript.adoc
Labels: Documentation

#3438 Filter "Error handling" GuiAction if transform doesn't support it #3436
  ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
Labels: Hop Gui

#3448 [ITA-TRANS] Fixed Italian Translations
  ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_it_IT.properties
Labels: Hop Gui

#3449 [DOCS] Updated Oracle driver's documentation by adding a missing detail
  docs/hop-user-manual/modules/ROOT/pages/database/databases/oracle.adoc
Labels: Documentation

#3455 [DOC] fix typo
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflow-logging.adoc
Labels: Documentation

#3459 Translations update from Weblate
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/window/messages/messages_pt_BR.properties
  plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/probe/meta/messages/messages_pt_BR.properties
  plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/reader/meta/messages/messages_pt_BR.properties
  plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/workflow/meta/messages/messages_pt_BR.properties
  plugins/transforms/concatfields/src/main/resources/org/apache/hop/pipeline/transforms/concatfields/messages/messages_pt_BR.properties
  plugins/transforms/excel/src/main/resources/org/apache/hop/pipeline/transforms/excelwriter/messages/messages_pt_BR.properties
  plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsonoutput/messages/messages_pt_BR.properties
  plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsonoutputenhanced/messages/messages_pt_BR.properties
  plugins/transforms/nullif/src/main/resources/org/apache/hop/pipeline/transforms/nullif/messages/messages_pt_BR.properties
  plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/textfileoutput/messages/messages_pt_BR.properties
  plugins/transforms/xml/src/main/resources/org/apache/hop/pipeline/transforms/xml/addxml/messages/messages_pt_BR.properties
  plugins/transforms/xml/src/main/resources/org/apache/hop/pipeline/transforms/xml/xmloutput/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/pipeline/dialog/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/workflow/actions/missing/messages/messages_pt_BR.properties
Labels: Hop Gui
