Repository apache/hop, pull requests merged in 2023-07, with the labels that each got.

#3053 fix #2998
  plugins/tech/azure/src/main/java/org/apache/hop/vfs/azure/config/AzureConfigPlugin.java
  plugins/tech/google/src/main/java/org/apache/hop/vfs/gs/config/GoogleCloudConfigPlugin.java
  ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/config/ExplorerPerspectiveConfigPlugin.java
  ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/explorer/messages/messages_en_US.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/explorer/messages/messages_it_IT.properties
Labels: Hop Gui

#3066 workflow and pipeline log how-to guides #3064 #3065
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/new-pipeline-log.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/pipeline-log-selection.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/pipeline-log-table.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/pipeline-log.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/pipeline-log2.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/pipeline-logging-transform.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/rdbms-connection.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/run-pipeline-logging.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/run-pipeline-table.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/run-pipeline-transform-metrics.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/sql-statements-execution.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/sql-statements.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-pipeline-log/table-output-properties.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/config-workflow-logging.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/pipeline-generate-rows.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/run-workflow-logging.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/run-workflow-metrics.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/run-workflow.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-log-selection.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-log-table.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-logging-config.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-logging-connection.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-logging-execute-sql.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-logging-new.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-logging-pipeline.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-logging-sql.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-logging-table-output.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-logging-table.jpg
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/logging-workflow-log/workflow-logging.jpg
  docs/hop-user-manual/modules/ROOT/nav.adoc
  docs/hop-user-manual/modules/ROOT/pages/how-to-guides/logging-pipeline-log.adoc
  docs/hop-user-manual/modules/ROOT/pages/how-to-guides/logging-workflow-log.adoc
Labels: Documentation

#3069 Change order nav.adoc, enable boolean/timestamp support mssql server
  docs/hop-user-manual/modules/ROOT/nav.adoc
  plugins/databases/mssqlnative/src/main/java/org/apache/hop/databases/mssqlnative/MsSqlServerNativeDatabaseMeta.java
Labels: Documentation

#3067 task #1992 Cleanup XML of action SNMP Trap
  assemblies/plugins/actions/snowflake/src/assembly/assembly.xml
  docker/integration-tests/integration-tests-snmp.yaml
  integration-tests/snmp/001-check-log.hpl
  integration-tests/snmp/dev-env-config.json
  integration-tests/snmp/hop-config.json
  integration-tests/snmp/main-001-snmp-trap-test.hwf
  integration-tests/snmp/metadata/pipeline-run-configuration/local.json
  integration-tests/snmp/metadata/workflow-run-configuration/local.json
  integration-tests/snmp/project-config.json
  plugins/actions/snmptrap/src/main/java/org/apache/hop/workflow/actions/snmptrap/ActionSNMPTrap.java
  plugins/actions/snmptrap/src/main/java/org/apache/hop/workflow/actions/snmptrap/ActionSNMPTrapDialog.java
  plugins/actions/snmptrap/src/test/java/org/apache/hop/workflow/actions/snmptrap/ActionSNMPTrapTest.java
  plugins/actions/snmptrap/src/test/java/org/apache/hop/workflow/actions/snmptrap/WorkflowActionSNMPTrapTest.java
  plugins/actions/snmptrap/src/test/resources/snmp-trap-action.xml
Labels: Containers, Integration Testing

#3074 Update setvariable.adoc to define what a default value is
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/setvariable.adoc
Labels: Documentation

#3076 mongoDb Delete widget disposed error and enable test, fixes #2971
  integration-tests/hopweb/src/test/resources/transforms.csv
  plugins/transforms/mongodb/src/main/java/org/apache/hop/pipeline/transforms/mongodbdelete/MongoDbDeleteDialog.java
Labels: Integration Testing

#3070 change tomcat user so it's non-root, fixes #2561
  docker/Dockerfile.web
Labels: Containers

#3048 fix #2256, #3043
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
  plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
  plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleImport.java
Labels: Documentation

#3081 document available variables in CTRL-Space popup. fixes #3080
  docs/hop-user-manual/modules/ROOT/pages/hop-gui/shortcuts.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/variables/control-space.adoc
  docs/hop-user-manual/modules/ROOT/pages/variables.adoc
Labels: Documentation

#3084 improved installation, configuration, upgrade guide. fixes #3042
  docs/hop-user-manual/modules/ROOT/assets/images/installation-configuration-windows-env-var-from-start.png
  docs/hop-user-manual/modules/ROOT/assets/images/installation-configuration-windows-env-var.png
  docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/variables/hop-options.adoc
Labels: Documentation

#3085 doc page renames, doc improvements for workflow and pipeline executor #3083
  docs/hop-user-manual/modules/ROOT/nav.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/pipeline-executor.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflow-executor.adoc
Labels: Documentation

#3096 updated variables and set variables doc pages #3095
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/setvariable.adoc
  docs/hop-user-manual/modules/ROOT/pages/variables.adoc
Labels: Documentation

#3101 Add file history to vfs-dialog, fixes #2222
  plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopGuiFileDefaultFolder.java
  ui/src/main/java/org/apache/hop/ui/core/PropsUi.java
Labels: Hop Gui

#3106 Auto-distributing doesn't activate the "Save" button #3102
  ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
  ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
  ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
  ui/src/main/java/org/apache/hop/ui/hopgui/perspective/dataorch/HopGuiAbstractGraph.java
Labels: bug, Hop Gui

#3115 In "Database Explorer", sort Schemas alphabetically #3112
  core/src/main/java/org/apache/hop/core/database/DatabaseMetaInformation.java
Labels: Database, Hop Gui
