Repository apache/hop, pull requests merged in 2023-12, with the labels that each got.

#3474 Translations update from Weblate
  plugins/actions/delay/src/main/resources/org/apache/hop/workflow/actions/delay/messages/messages_pt_BR.properties
  plugins/actions/evaluatetablecontent/src/main/resources/org/apache/hop/workflow/actions/evaluatetablecontent/messages/messages_pt_BR.properties
  plugins/actions/mssqlbulkload/src/main/resources/org/apache/hop/workflow/actions/mssqlbulkload/messages/messages_pt_BR.properties
  plugins/actions/mysqlbulkload/src/main/resources/org/apache/hop/workflow/actions/mysqlbulkload/messages/messages_pt_BR.properties
  plugins/actions/waitforsql/src/main/resources/org/apache/hop/workflow/actions/waitforsql/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/gui/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/window/messages/messages_pt_BR.properties
  plugins/misc/projects/src/main/resources/org/apache/hop/projects/gui/messages/messages_pt_BR.properties
  plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/probe/gui/messages/messages_pt_BR.properties
  plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/reader/meta/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/execution/messages/messages_pt_BR.properties
  plugins/transforms/fake/src/main/resources/org/apache/hop/pipeline/transforms/fake/messages/messages_pt_BR.properties
  plugins/transforms/mapping/src/main/resources/org/apache/hop/pipeline/transforms/input/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/file/pipeline/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/file/workflow/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/metadata/messages/messages_pt_BR.properties
Labels: Hop Gui, Neo4j

#3476 Translations update from Weblate
  engine/src/main/resources/org/apache/hop/execution/sampler/plugins/dataprof/messages/messages_pt_BR.properties
  engine/src/main/resources/org/apache/hop/execution/sampler/plugins/messages/messages_pt_BR.properties
  plugins/actions/delay/src/main/resources/org/apache/hop/workflow/actions/delay/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/kafka/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/pubsub/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/execution/messages/messages_pt_BR.properties
  plugins/transforms/coalesce/src/main/resources/org/apache/hop/pipeline/transforms/coalesce/messages/messages_pt_BR.properties
  plugins/transforms/denormaliser/src/main/resources/org/apache/hop/pipeline/transforms/denormaliser/messages/messages_pt_BR.properties
  plugins/transforms/flattener/src/main/resources/org/apache/hop/pipeline/transforms/flattener/messages/messages_pt_BR.properties
  plugins/transforms/groupby/src/main/resources/org/apache/hop/pipeline/transforms/groupby/messages/messages_pt_BR.properties
  plugins/transforms/memgroupby/src/main/resources/org/apache/hop/pipeline/transforms/memgroupby/messages/messages_pt_BR.properties
  plugins/transforms/tokenreplacement/src/main/resources/org/apache/hop/pipeline/transforms/tokenreplacement/messages/messages_pt_BR.properties
Labels: Neo4j

#3479 Translations update from Weblate
  core/src/main/resources/org/apache/hop/core/messages/messages_pt_BR.properties
  plugins/actions/dostounix/src/main/resources/org/apache/hop/workflow/actions/dostounix/messages/messages_pt_BR.properties
  plugins/actions/simpleeval/src/main/resources/org/apache/hop/workflow/actions/simpleeval/messages/messages_pt_BR.properties
  plugins/actions/snowflake/src/main/resources/org/apache/hop/workflow/actions/snowflake/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/engines/flink/messages/messages_pt_BR.properties
  plugins/misc/reflection/src/main/resources/org/apache/hop/reflection/probe/gui/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/perspective/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/transforms/cypher/messages/messages_pt_BR.properties
  plugins/transforms/checksum/src/main/resources/org/apache/hop/pipeline/transforms/checksum/messages/messages_pt_BR.properties
  plugins/transforms/coalesce/src/main/resources/org/apache/hop/pipeline/transforms/coalesce/messages/messages_pt_BR.properties
  plugins/transforms/creditcardvalidator/src/main/resources/org/apache/hop/pipeline/transforms/creditcardvalidator/messages/messages_pt_BR.properties
  plugins/transforms/detectlastrow/src/main/resources/org/apache/hop/pipeline/transforms/detectlastrow/messages/messages_pt_BR.properties
  plugins/transforms/excel/src/main/resources/org/apache/hop/pipeline/transforms/excelwriter/messages/messages_pt_BR.properties
  plugins/transforms/execprocess/src/main/resources/org/apache/hop/pipeline/transforms/execprocess/messages/messages_pt_BR.properties
  plugins/transforms/fieldschangesequence/src/main/resources/org/apache/hop/pipeline/transforms/fieldschangesequence/messages/messages_pt_BR.properties
  plugins/transforms/fileexists/src/main/resources/org/apache/hop/pipeline/transforms/fileexists/messages/messages_pt_BR.properties
  plugins/transforms/filelocked/src/main/resources/org/apache/hop/pipeline/transforms/filelocked/messages/messages_pt_BR.properties
  plugins/transforms/formula/src/main/resources/org/apache/hop/pipeline/transforms/formula/messages/messages_pt_BR.properties
  plugins/transforms/getsubfolders/src/main/resources/org/apache/hop/pipeline/transforms/getsubfolders/messages/messages_pt_BR.properties
  plugins/transforms/httppost/src/main/resources/org/apache/hop/pipeline/transforms/httppost/messages/messages_pt_BR.properties
  plugins/transforms/ifnull/src/main/resources/org/apache/hop/pipeline/transforms/ifnull/messages/messages_pt_BR.properties
  plugins/transforms/insertupdate/src/main/resources/org/apache/hop/pipeline/transforms/insertupdate/messages/messages_pt_BR.properties
  plugins/transforms/janino/src/main/resources/org/apache/hop/pipeline/transforms/userdefinedjavaclass/messages/messages_pt_BR.properties
  plugins/transforms/javascript/src/main/resources/org/apache/hop/pipeline/transforms/javascript/messages/messages_pt_BR.properties
  plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsoninput/messages/messages_pt_BR.properties
  plugins/transforms/ldap/src/main/resources/org/apache/hop/pipeline/transforms/ldapinput/messages/messages_pt_BR.properties
  plugins/transforms/mapping/src/main/resources/org/apache/hop/pipeline/transforms/mapping/messages/messages_pt_BR.properties
  plugins/transforms/memgroupby/src/main/resources/org/apache/hop/pipeline/transforms/memgroupby/messages/messages_pt_BR.properties
  plugins/transforms/monetdbbulkloader/src/main/resources/org/apache/hop/pipeline/transforms/monetdbbulkloader/messages/messages_pt_BR.properties
  plugins/transforms/mongodb/src/main/resources/org/apache/hop/pipeline/transforms/mongodbinput/messages/messages_pt_BR.properties
  plugins/transforms/orabulkloader/src/main/resources/org/apache/hop/pipeline/transforms/orabulkloader/messages/messages_pt_BR.properties
  plugins/transforms/pgbulkloader/src/main/resources/org/apache/hop/pipeline/transforms/pgbulkloader/messages/messages_pt_BR.properties
  plugins/transforms/pgp/src/main/resources/org/apache/hop/pipeline/transforms/pgpdecryptstream/messages/messages_pt_BR.properties
  plugins/transforms/pgp/src/main/resources/org/apache/hop/pipeline/transforms/pgpencryptstream/messages/messages_pt_BR.properties
  plugins/transforms/pipelineexecutor/src/main/resources/org/apache/hop/pipeline/transforms/pipelineexecutor/messages/messages_pt_BR.properties
  plugins/transforms/propertyoutput/src/main/resources/org/apache/hop/pipeline/transforms/propertyoutput/messages/messages_pt_BR.properties
  plugins/transforms/rest/src/main/resources/org/apache/hop/pipeline/transforms/rest/messages/messages_pt_BR.properties
  plugins/transforms/setvalueconstant/src/main/resources/org/apache/hop/pipeline/transforms/setvalueconstant/messages/messages_pt_BR.properties
  plugins/transforms/sort/src/main/resources/org/apache/hop/pipeline/transforms/sort/messages/messages_pt_BR.properties
  plugins/transforms/sqlfileoutput/src/main/resources/org/apache/hop/pipeline/transforms/sqlfileoutput/messages/messages_pt_BR.properties
  plugins/transforms/streamlookup/src/main/resources/org/apache/hop/pipeline/transforms/streamlookup/messages/messages_pt_BR.properties
  plugins/transforms/streamschemamerge/src/main/resources/org/apache/hop/pipeline/transforms/streamschemamerge/messages/messages_pt_BR.properties
  plugins/transforms/stringoperations/src/main/resources/org/apache/hop/pipeline/transforms/stringoperations/messages/messages_pt_BR.properties
  plugins/transforms/tableexists/src/main/resources/org/apache/hop/pipeline/transforms/tableexists/messages/messages_pt_BR.properties
  plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/textfileoutput/messages/messages_pt_BR.properties
  plugins/transforms/uniquerows/src/main/resources/org/apache/hop/pipeline/transforms/uniquerows/messages/messages_pt_BR.properties
  plugins/transforms/uniquerowsbyhashset/src/main/resources/org/apache/hop/pipeline/transforms/uniquerowsbyhashset/messages/messages_pt_BR.properties
  plugins/transforms/validator/src/main/resources/org/apache/hop/pipeline/transforms/validator/messages/messages_pt_BR.properties
  plugins/transforms/webserviceavailable/src/main/resources/org/apache/hop/pipeline/transforms/webserviceavailable/messages/messages_pt_BR.properties
  plugins/transforms/workflowexecutor/src/main/resources/org/apache/hop/pipeline/transforms/workflowexecutor/messages/messages_pt_BR.properties
  plugins/transforms/writetolog/src/main/resources/org/apache/hop/pipeline/transforms/writetolog/messages/messages_pt_BR.properties
  plugins/transforms/xml/src/main/resources/org/apache/hop/pipeline/transforms/xml/getxmldata/messages/messages_pt_BR.properties
  plugins/transforms/xml/src/main/resources/org/apache/hop/pipeline/transforms/xml/xmloutput/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/core/database/dialog/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/core/dialog/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/core/widget/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/dialog/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/pipeline/dialog/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/pipeline/transform/common/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/workflow/dialog/messages/messages_pt_BR.properties
Labels: Hop Gui, Neo4j

#3466 Update formula.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
Labels: Documentation

#3467 Update writetolog.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/writetolog.adoc
Labels: Documentation

#3468 Update getvariable.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc
Labels: Documentation

#3473 Update filterrows.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/filterrows.adoc
Labels: Documentation

#3444 Update tableinput.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/tableinput.adoc
Labels: Documentation

#3445 Update formula.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
Labels: Documentation

#3446 Filter "Specify copies" GuiAction if transform doesn't support it #3439
  engine/src/main/java/org/apache/hop/pipeline/transform/BaseTransformMeta.java
  engine/src/main/java/org/apache/hop/pipeline/transform/ITransformMeta.java
  engine/src/main/java/org/apache/hop/pipeline/transform/TransformMeta.java
  plugins/transforms/abort/src/main/java/org/apache/hop/pipeline/transforms/abort/AbortMeta.java
  plugins/transforms/analyticquery/src/main/java/org/apache/hop/pipeline/transforms/analyticquery/AnalyticQueryMeta.java
  plugins/transforms/groupby/src/main/java/org/apache/hop/pipeline/transforms/groupby/GroupByMeta.java
  plugins/transforms/memgroupby/src/main/java/org/apache/hop/pipeline/transforms/memgroupby/MemoryGroupByMeta.java
  ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
Labels: Hop Gui, Transforms

#3501 Translations update from Weblate
  engine/src/main/resources/org/apache/hop/www/messages/messages_pt_BR.properties
  plugins/actions/addresultfilenames/src/main/resources/org/apache/hop/workflow/actions/addresultfilenames/messages/messages_pt_BR.properties
  plugins/actions/copymoveresultfilenames/src/main/resources/org/apache/hop/workflow/actions/copymoveresultfilenames/messages/messages_pt_BR.properties
  plugins/actions/ftp/src/main/resources/org/apache/hop/workflow/actions/ftp/messages/messages_pt_BR.properties
  plugins/actions/ftp/src/main/resources/org/apache/hop/workflow/actions/ftpdelete/messages/messages_pt_BR.properties
  plugins/actions/ftp/src/main/resources/org/apache/hop/workflow/actions/ftpput/messages/messages_pt_BR.properties
  plugins/actions/ftp/src/main/resources/org/apache/hop/workflow/actions/sftp/messages/messages_pt_BR.properties
  plugins/actions/ftp/src/main/resources/org/apache/hop/workflow/actions/sftpput/messages/messages_pt_BR.properties
  plugins/actions/getpop/src/main/resources/org/apache/hop/workflow/actions/getpop/messages/messages_pt_BR.properties
  plugins/actions/mail/src/main/resources/org/apache/hop/workflow/actions/mail/messages/messages_pt_BR.properties
  plugins/actions/writetofile/src/main/resources/org/apache/hop/workflow/actions/writetofile/messages/messages_pt_BR.properties
  plugins/actions/zipfile/src/main/resources/org/apache/hop/workflow/actions/zipfile/messages/messages_pt_BR.properties
  plugins/tech/cassandra/src/main/resources/org/apache/hop/pipeline/transforms/cassandrainput/messages/messages_pt_BR.properties
  plugins/transforms/blockingtransform/src/main/resources/org/apache/hop/pipeline/transforms/blockingtransform/messages/messages_pt_BR.properties
  plugins/transforms/combinationlookup/src/main/resources/org/apache/hop/pipeline/transforms/combinationlookup/messages/messages_pt_BR.properties
  plugins/transforms/databaselookup/src/main/resources/org/apache/hop/pipeline/transforms/databaselookup/messages/messages_pt_BR.properties
  plugins/transforms/dimensionlookup/src/main/resources/org/apache/hop/pipeline/transforms/dimensionlookup/messages/messages_pt_BR.properties
  plugins/transforms/excel/src/main/resources/org/apache/hop/pipeline/transforms/excelwriter/messages/messages_pt_BR.properties
  plugins/transforms/fieldsplitter/src/main/resources/org/apache/hop/pipeline/transforms/fieldsplitter/messages/messages_pt_BR.properties
  plugins/transforms/getfilesrowcount/src/main/resources/org/apache/hop/pipeline/transforms/getfilesrowcount/messages/messages_pt_BR.properties
  plugins/transforms/getsubfolders/src/main/resources/org/apache/hop/pipeline/transforms/getsubfolders/messages/messages_pt_BR.properties
  plugins/transforms/gettablenames/src/main/resources/org/apache/hop/pipeline/transforms/gettablenames/messages/messages_pt_BR.properties
  plugins/transforms/groupby/src/main/resources/org/apache/hop/pipeline/transforms/groupby/messages/messages_pt_BR.properties
  plugins/transforms/httppost/src/main/resources/org/apache/hop/pipeline/transforms/httppost/messages/messages_pt_BR.properties
  plugins/transforms/kafka/src/main/resources/org/apache/hop/pipeline/transforms/kafka/consumer/messages/messages_pt_BR.properties
  plugins/transforms/kafka/src/main/resources/org/apache/hop/pipeline/transforms/kafka/producer/messages/messages_pt_BR.properties
  plugins/transforms/ldap/src/main/resources/org/apache/hop/pipeline/transforms/ldapinput/messages/messages_pt_BR.properties
  plugins/transforms/ldap/src/main/resources/org/apache/hop/pipeline/transforms/ldapoutput/messages/messages_pt_BR.properties
  plugins/transforms/loadfileinput/src/main/resources/org/apache/hop/pipeline/transforms/loadfileinput/messages/messages_pt_BR.properties
  plugins/transforms/mail/src/main/resources/org/apache/hop/pipeline/transforms/mail/messages/messages_pt_BR.properties
  plugins/transforms/mailinput/src/main/resources/org/apache/hop/pipeline/transforms/mailinput/messages/messages_pt_BR.properties
  plugins/transforms/mapping/src/main/resources/org/apache/hop/pipeline/transforms/mapping/messages/messages_pt_BR.properties
  plugins/transforms/metainject/src/main/resources/org/apache/hop/pipeline/transforms/metainject/messages/messages_pt_BR.properties
  plugins/transforms/metastructure/src/main/resources/org/apache/hop/pipeline/transforms/metastructure/messages/messages_pt_BR.properties
  plugins/transforms/mongodb/src/main/resources/org/apache/hop/pipeline/transforms/mongodbinput/messages/messages_pt_BR.properties
  plugins/transforms/mongodb/src/main/resources/org/apache/hop/pipeline/transforms/mongodboutput/messages/messages_pt_BR.properties
  plugins/transforms/orabulkloader/src/main/resources/org/apache/hop/pipeline/transforms/orabulkloader/messages/messages_pt_BR.properties
  plugins/transforms/pgbulkloader/src/main/resources/org/apache/hop/pipeline/transforms/pgbulkloader/messages/messages_pt_BR.properties
  plugins/transforms/propertyoutput/src/main/resources/org/apache/hop/pipeline/transforms/propertyoutput/messages/messages_pt_BR.properties
  plugins/transforms/regexeval/src/main/resources/org/apache/hop/pipeline/transforms/regexeval/messages/messages_pt_BR.properties
  plugins/transforms/rest/src/main/resources/org/apache/hop/pipeline/transforms/rest/messages/messages_pt_BR.properties
  plugins/transforms/salesforce/src/main/resources/org/apache/hop/pipeline/transforms/salesforce/messages/messages_pt_BR.properties
  plugins/transforms/ssh/src/main/resources/org/apache/hop/pipeline/transforms/ssh/messages/messages_pt_BR.properties
  plugins/transforms/streamlookup/src/main/resources/org/apache/hop/pipeline/transforms/streamlookup/messages/messages_pt_BR.properties
  plugins/transforms/streamschemamerge/src/main/resources/org/apache/hop/pipeline/transforms/streamschemamerge/messages/messages_pt_BR.properties
  plugins/transforms/stringoperations/src/main/resources/org/apache/hop/pipeline/transforms/stringoperations/messages/messages_pt_BR.properties
  plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/textfileoutput/messages/messages_pt_BR.properties
  plugins/transforms/tika/src/main/resources/org/apache/hop/pipeline/transforms/tika/messages/messages_pt_BR.properties
  plugins/transforms/webservices/src/main/resources/org/apache/hop/pipeline/transforms/webservices/messages/messages_pt_BR.properties
  plugins/transforms/xml/src/main/resources/org/apache/hop/pipeline/transforms/xml/getxmldata/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/core/dialog/messages/messages_pt_BR.properties
Labels: Hop Gui

#3513 Translations update from Weblate
  plugins/actions/ftp/src/main/resources/org/apache/hop/workflow/actions/ftp/messages/messages_pt_BR.properties
  plugins/actions/ftp/src/main/resources/org/apache/hop/workflow/actions/ftpdelete/messages/messages_pt_BR.properties
  plugins/actions/ftp/src/main/resources/org/apache/hop/workflow/actions/ftpput/messages/messages_pt_BR.properties
  plugins/actions/ftp/src/main/resources/org/apache/hop/workflow/actions/sftpput/messages/messages_pt_BR.properties
  plugins/actions/webserviceavailable/src/main/resources/org/apache/hop/workflow/actions/webserviceavailable/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/metadata/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/bigtable/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/bq/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/kafka/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/kinesis/messages/messages_pt_BR.properties
  plugins/tech/avro/src/main/resources/org/apache/hop/avro/transforms/avrodecode/messages/messages_pt_BR.properties
  plugins/tech/avro/src/main/resources/org/apache/hop/avro/transforms/avrooutput/messages/messages_pt_BR.properties
  plugins/tech/cassandra/src/main/resources/org/apache/hop/pipeline/transforms/cassandraoutput/messages/messages_pt_BR.properties
  plugins/tech/cassandra/src/main/resources/org/apache/hop/pipeline/transforms/cassandrasstableoutput/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/actions/constraint/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/actions/cypherscript/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/actions/index/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/model/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/perspective/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/shared/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/transforms/cypher/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/transforms/cypherbuilder/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/transforms/graph/messages/messages_pt_BR.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/transforms/output/messages/messages_pt_BR.properties
  plugins/tech/parquet/src/main/resources/org/apache/hop/parquet/transforms/output/messages/messages_pt_BR.properties
  plugins/transforms/dynamicsqlrow/src/main/resources/org/apache/hop/pipeline/transforms/dynamicsqlrow/messages/messages_pt_BR.properties
  plugins/transforms/fieldschangesequence/src/main/resources/org/apache/hop/pipeline/transforms/fieldschangesequence/messages/messages_pt_BR.properties
  plugins/transforms/filelocked/src/main/resources/org/apache/hop/pipeline/transforms/filelocked/messages/messages_pt_BR.properties
  plugins/transforms/getfilenames/src/main/resources/org/apache/hop/pipeline/transforms/getfilenames/messages/messages_pt_BR.properties
  plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsoninput/messages/messages_pt_BR.properties
  plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsonoutput/messages/messages_pt_BR.properties
  plugins/transforms/json/src/main/resources/org/apache/hop/pipeline/transforms/jsonoutputenhanced/messages/messages_pt_BR.properties
  plugins/transforms/memgroupby/src/main/resources/org/apache/hop/pipeline/transforms/memgroupby/messages/messages_pt_BR.properties
  plugins/transforms/mergerows/src/main/resources/org/apache/hop/pipeline/transforms/mergerows/messages/messages_pt_BR.properties
  plugins/transforms/processfiles/src/main/resources/org/apache/hop/pipeline/transforms/processfiles/messages/messages_pt_BR.properties
  plugins/transforms/switchcase/src/main/resources/org/apache/hop/pipeline/transforms/switchcase/messages/messages_pt_BR.properties
  plugins/transforms/update/src/main/resources/org/apache/hop/pipeline/transforms/update/messages/messages_pt_BR.properties
  plugins/transforms/workflowexecutor/src/main/resources/org/apache/hop/pipeline/transforms/workflowexecutor/messages/messages_pt_BR.properties
Labels: Neo4j

#3483 Update formula.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
Labels: Documentation

#3523 #3522 Add documentation cross references from Getting Started - Hop Tools to other documentation
  docs/hop-user-manual/modules/ROOT/pages/getting-started/hop-tools.adoc
Labels: Documentation

#3481 Update pipeline.adoc
  docs/hop-user-manual/modules/ROOT/pages/workflow/actions/pipeline.adoc
Labels: Documentation

#3506 Update joinrows.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/joinrows.adoc
Labels: Documentation

#3480 Update copyrowstoresult.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/copyrowstoresult.adoc
Labels: Documentation

#3528 Fix Google Sheets output category #3525
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutputMeta.java
Labels: Transforms

#3519 Fix #3517, Task #3519
  assemblies/lib-jdbc/pom.xml
  plugins/databases/duckdb/pom.xml
  ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/ExecutionPerspective.java
Labels: Hop Gui
