Repository apache/hop, pull requests merged in 2023-04, with the labels that each got.

#2805 [Doc] Replace Jira ticket by Github issue
  docs/hop-user-manual/modules/ROOT/pages/index.adoc
Labels: Documentation

#2815 added metadata injection samples, extended documentation. fixes #2784
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/filterrows.adoc
  plugins/transforms/filterrows/src/main/samples/metadata-injection/filter-rows-mdi-child.hpl
  plugins/transforms/filterrows/src/main/samples/metadata-injection/filter-rows-mdi-parent.hpl
Labels: Documentation

#2818 Translations update from Weblate
  plugins/actions/success/src/main/resources/org/apache/hop/workflow/actions/success/messages/messages_de_DE.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/shared/messages/messages_de_DE.properties
  ui/src/main/resources/org/apache/hop/ui/core/database/messages/messages_de_DE.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/dialog/messages/messages_de_DE.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/welcome/messages/messages_de_DE.properties
  ui/src/main/resources/org/apache/hop/ui/workflow/config/messages/messages_de_DE.properties
  ui/src/main/resources/org/apache/hop/ui/workflow/dialog/messages/messages_de_DE.properties
Labels: Hop Gui, Neo4j

#2821 [DOC] add hop-web Beam version to release documentation
  docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc
Labels: Documentation

#2847 how-to guide on loops in Apache Hop #2559
  assemblies/static/src/main/resources/config/projects/samples/loops/child-check-set-counter-value.hpl
  assemblies/static/src/main/resources/config/projects/samples/loops/child-generate-1000-rows.hpl
  assemblies/static/src/main/resources/config/projects/samples/loops/child-loops-copy-rows-to-result.hpl
  assemblies/static/src/main/resources/config/projects/samples/loops/child-loops-get-rows-from-result.hpl
  assemblies/static/src/main/resources/config/projects/samples/loops/child-loops-log-counter.hpl
  assemblies/static/src/main/resources/config/projects/samples/loops/child-workflow-executor.hwf
  assemblies/static/src/main/resources/config/projects/samples/loops/end-repeat-pipeline.hwf
  assemblies/static/src/main/resources/config/projects/samples/loops/loops-process-rows-from-memory.hwf
  assemblies/static/src/main/resources/config/projects/samples/loops/pipeline-executor.hpl
  assemblies/static/src/main/resources/config/projects/samples/loops/repeat-action.hwf
  assemblies/static/src/main/resources/config/projects/samples/loops/workflow-executor.hpl
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-copy-rows-to-result-execute-for-every-result-row.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-copy-rows-to-result-parameters.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-copy-rows-to-result-process-one-row.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-copy-rows-to-result-workflow.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-copy-rows-to-result.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-pipeline-executor-configuration.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-pipeline-executor.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-repeat-action.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-repeat-pipeline.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-workflow-executor-configuration.png
  docs/hop-user-manual/modules/ROOT/assets/images/how-to-guides/loops-in-apache-hop/loops-workflow-executor.png
  docs/hop-user-manual/modules/ROOT/nav.adoc
  docs/hop-user-manual/modules/ROOT/pages/how-to-guides/index.adoc
  docs/hop-user-manual/modules/ROOT/pages/how-to-guides/loops-in-apache-hop.adoc
Labels: Documentation

#2843 updated documatation for pop3/imap action. fixes #2659
  docs/hop-user-manual/modules/ROOT/nav.adoc
  docs/hop-user-manual/modules/ROOT/pages/workflow/actions/getpop.adoc
Labels: Documentation

#2837 fix #2806
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/databaselookup.adoc
Labels: Documentation

#2872 fix json input transform error #2870, update snowflake jdbc driver #2871, Json output fix #2839
  assemblies/plugins/actions/snowflake/pom.xml
  assemblies/plugins/databases/snowflake-assemblies/pom.xml
  assemblies/plugins/tech/azure/pom.xml
  assemblies/plugins/transforms/json/pom.xml
  assemblies/plugins/transforms/snowflake/pom.xml
  integration-tests/json/0003-json-test-block-size.hpl
  integration-tests/json/0003-json-write-block-size.hpl
  integration-tests/json/0004-json-write-block-size-in-field.hpl
  integration-tests/json/main-0003-json-test-block-size.hwf
  integration-tests/json/main-0004-json-test-block-size-in-field.hwf
  plugins/transforms/json/pom.xml
  plugins/transforms/json/src/main/java/org/apache/hop/pipeline/transforms/jsonoutput/JsonOutput.java
  plugins/transforms/snowflake/pom.xml
  pom.xml
Labels: Integration Testing

#2873 fix #2817
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/enhancedjsonoutput.adoc
  plugins/transforms/json/src/main/samples/transforms/json-output-generate-nested-structure.hpl
Labels: Documentation

#2882 fix #2877
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflowexecutor.adoc
Labels: Documentation

#2885 Simplify the Hop Web image including beam, fixes #2884
  Jenkinsfile
  docker/Dockerfile.web-fatjar
Labels: Containers

#2887 special characters in graph properties, exclude child hpl/hwf from samples IT #2812 #2237
  docker/integration-tests/integration-tests-neo4j.yaml
  integration-tests/neo4j/dev-env-config.json
  integration-tests/neo4j/metadata/neo4j-graph-model/model-2812.json
  integration-tests/neo4j/tests/neo4j-2812-graph-model-with-spaces-in-key-names/2812-check-graph.hpl
  integration-tests/neo4j/tests/neo4j-2812-graph-model-with-spaces-in-key-names/2812-model-with-spaces-in-key-names.hpl
  integration-tests/neo4j/tests/neo4j-2812-graph-model-with-spaces-in-key-names/main-2812-model-with-spaces-in-key-names.hwf
  integration-tests/samples/read-samples-build-hop-run.hpl
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/graph/GraphOutput.java
Labels: Containers, Integration Testing, Neo4j

#2892 changed JIRA links to GitHub issues links. fixes #2891
  CONTRIBUTING.md
  docs/hop-user-manual/modules/ROOT/pages/installation-configuration.adoc
  docs/hop-user-manual/modules/ROOT/pages/supported-jvms.adoc
Labels: Documentation
