Repository apache/hop, pull requests merged in 2023-09, with the labels that each got.

#3197 JSON input samples and updated docs #2237
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/jsoninput.adoc
  plugins/transforms/json/src/main/samples/transforms/json-input-basic.hpl
  plugins/transforms/json/src/main/samples/transforms/json-input-nested-elements.hpl
Labels: Documentation

#3181 Ability to start workflow at specific action via hop-run #3178
  docs/hop-user-manual/modules/ROOT/pages/hop-run/index.adoc
  engine/src/main/java/org/apache/hop/run/HopRun.java
Labels: Hop Run

#3177 Update execinfo.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/execinfo.adoc
Labels: Documentation

#3182 Update getvariable.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc
Labels: Documentation

#3186 Update datagrid.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/datagrid.adoc
Labels: Documentation

#3187 Update rowgenerator.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/rowgenerator.adoc
Labels: Documentation

#3191 Update formula.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/formula.adoc
Labels: Documentation

#3199 Fixes around MS Sql Server
  docs/hop-user-manual/modules/ROOT/assets/images/database/databases/mssqlnative/hop_connection.png
  docs/hop-user-manual/modules/ROOT/assets/images/database/databases/mssqlnative/hop_connection_options_tab.png
  docs/hop-user-manual/modules/ROOT/assets/images/database/databases/mssqlnative/sqlserver_configuration.png
  docs/hop-user-manual/modules/ROOT/pages/database/databases/mssqlnative.adoc
  plugins/databases/mssqlnative/src/main/java/org/apache/hop/databases/mssqlnative/MsSqlServerNativeDatabaseMeta.java
Labels: Documentation

#3190 beam and bigtable version updates. fixes #3188
  assemblies/plugins/engines/beam/pom.xml
  docs/hop-user-manual/modules/ROOT/pages/pipeline/beam/getting-started-with-beam.adoc
  plugins/engines/beam/pom.xml
  pom.xml
Labels: Documentation

#3201 google sheets - additional options, doc updates and updates/fixes #3034
  assemblies/plugins/tech/google/pom.xml
  assemblies/plugins/tech/google/src/assembly/assembly.xml
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/google-sheets-input.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/google-sheets-output.adoc
  integration-tests/spreadsheet/0009-read-google-sheet.hpl
  integration-tests/spreadsheet/0010-write-google-sheet.hpl
  plugins/misc/import/src/main/java/org/apache/hop/imports/gui/HopImportGuiPlugin.java
  plugins/misc/import/src/main/java/org/apache/hop/imports/kettle/KettleConst.java
  plugins/tech/google/pom.xml
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsCredentials.java
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInput.java
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInputDialog.java
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInputMeta.java
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutput.java
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutputDialog.java
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutputMeta.java
Labels: Documentation, Integration Testing

#3204 Improve the way we get the list of DB procedures for oracle #3202
  plugins/databases/oracle/src/main/java/org/apache/hop/databases/oracle/OracleDatabaseMeta.java
  plugins/databases/oracle/src/test/java/org/apache/hop/databases/oracle/OracleDatabaseMetaTest.java
Labels: Database

#3206 allow limit size 0 to fetch all rows. fixes #3205
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/google-analytics.adoc
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googleanalytics/GoogleAnalytics.java
Labels: Documentation

#3215 Update getvariable.adoc - Adding whitespace
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/getvariable.adoc
Labels: Documentation

#3193 Update setvariable.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/setvariable.adoc
Labels: Documentation

#3203 Update pipeline-executor.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/pipeline-executor.adoc
Labels: Documentation

#3246 Connection is not visible in Snowflake bulk loader #3244
  plugins/transforms/snowflake/src/main/java/org/apache/hop/pipeline/transforms/snowflake/bulkloader/SnowflakeBulkLoaderDialog.java
Labels: Transforms

#3251 allow formula transform to use fields created in previous transforms.… #3239
  integration-tests/transforms/0042-formula-use-fields-created-in-previous-formula.hpl
  integration-tests/transforms/datasets/golden-formula-use-fields-created-in-previous-formula.csv
  integration-tests/transforms/main-0042-formula-use-fields-created-in-previous-formula.hwf
  integration-tests/transforms/metadata/dataset/golden-formula-use-fields-created-in-previous-formula.json
  integration-tests/transforms/metadata/unit-test/0042-formula-use-fields-created-in-previous-formula UNIT.json
  plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/Formula.java
Labels: Integration Testing

#3276 Documentation fix and dependency upgrades
  assemblies/plugins/misc/git/pom.xml
  assemblies/plugins/tech/parquet/pom.xml
  docs/hop-user-manual/modules/ROOT/pages/database/databases/monetdb.adoc
  engine-beam/pom.xml
  plugins/misc/git/pom.xml
  pom.xml
Labels: Beam, Documentation

#3273 fixes to allow nested formulas on previously replaced fields #3239
  integration-tests/transforms/0042-formula-nested-replace.hpl
  integration-tests/transforms/datasets/golden-formula-nested-replace.csv
  integration-tests/transforms/main-0042-formula-nested-replace.hwf
  integration-tests/transforms/metadata/dataset/golden-formula-nested-replace.json
  integration-tests/transforms/metadata/unit-test/0042-formula-nested-replace UNIT.json
  plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/Formula.java
  plugins/transforms/formula/src/main/java/org/apache/hop/pipeline/transforms/formula/util/FormulaParser.java
Labels: Integration Testing
