Repository apache/hop, pull requests merged in 2024-06, with the labels that each got.

#4005 Bump org.eclipse.platform to the last version #4004
  assemblies/client/pom.xml
  pom.xml
Labels: dependencies

#4014 Add jdbc drivers to Hop Web, fixes #4013
  .dockerignore
  Jenkinsfile
  docker/Dockerfile.web
  docker/create_hop_web_container.sh
  docs/hop-dev-manual/modules/ROOT/pages/apache-release/promoting-a-release.adoc
Labels: Containers, Documentation

#3993 Fixed typo!
  docs/hop-user-manual/modules/ROOT/pages/variables.adoc
Labels: Documentation

#3980 Fix #3321 improved documentation
  docs/hop-user-manual/modules/ROOT/pages/workflow/actions/setvariables.adoc
  plugins/actions/setvariables/src/main/samples/actions/variable_substitution.hwf
  plugins/actions/setvariables/src/main/samples/files/properties_file.properties
Labels: Documentation

#4019 Use compare using values by default in Unique rows hashset #3908
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/uniquerowsbyhashset.adoc
  plugins/transforms/uniquerowsbyhashset/src/main/java/org/apache/hop/pipeline/transforms/uniquerowsbyhashset/UniqueRowsByHashSetMeta.java
Labels: Documentation

#4027 update maven dependencies + cleanup, fixes #4026
  core/pom.xml
  engine/pom.xml
  plugins/actions/pom.xml
  plugins/databases/cockroachdb/pom.xml
  plugins/databases/cratedb/pom.xml
  plugins/databases/greenplum/pom.xml
  plugins/databases/pom.xml
  plugins/databases/postgresql/pom.xml
  plugins/databases/redshift/pom.xml
  plugins/tech/pom.xml
  plugins/transforms/pom.xml
  pom.xml
  ui/pom.xml
Labels: Hop Gui

#4033 Update to junit 5 and POM cleanup, #2616
  assemblies/lib-beam/pom.xml
  core/pom.xml
  core/src/test/java/org/apache/hop/core/logging/LogChannelTest.java
  core/src/test/java/org/apache/hop/core/row/ValueMetaAndDataTest.java
  core/src/test/java/org/apache/hop/core/xml/XmlHandlerUnitTest.java
  engine-beam/pom.xml
  engine/pom.xml
  plugins/actions/mailvalidator/pom.xml
  plugins/actions/pom.xml
  plugins/databases/pom.xml
  plugins/engines/beam/pom.xml
  plugins/misc/async/pom.xml
  plugins/misc/debug/pom.xml
  plugins/misc/git/pom.xml
  plugins/misc/import/pom.xml
  plugins/misc/passwords/pom.xml
  plugins/misc/projects/pom.xml
  plugins/misc/reflection/pom.xml
  plugins/misc/static-schema/pom.xml
  plugins/misc/testing/pom.xml
  plugins/tech/avro/pom.xml
  plugins/tech/aws/pom.xml
  plugins/tech/azure/pom.xml
  plugins/tech/cassandra/pom.xml
  plugins/tech/dropbox/pom.xml
  plugins/tech/google/pom.xml
  plugins/tech/neo4j/pom.xml
  plugins/tech/parquet/pom.xml
  plugins/tech/pom.xml
  plugins/transforms/dorisbulkloader/pom.xml
  plugins/transforms/excel/pom.xml
  plugins/transforms/http/pom.xml
  plugins/transforms/httppost/pom.xml
  plugins/transforms/janino/pom.xml
  plugins/transforms/json/pom.xml
  plugins/transforms/kafka/pom.xml
  plugins/transforms/memgroupby/pom.xml
  plugins/transforms/metainject/pom.xml
  plugins/transforms/mongodb/pom.xml
  plugins/transforms/pom.xml
  plugins/transforms/rest/pom.xml
  plugins/transforms/salesforce/pom.xml
  plugins/transforms/sasinput/pom.xml
  plugins/transforms/selectvalues/pom.xml
  plugins/transforms/serverstatus/pom.xml
  pom.xml
  ui/pom.xml
  ui/src/test/java/org/apache/hop/ui/util/EnvironmentUtilsTest.java
Labels: Beam, Hop Gui, Neo4j

#4032 Add icon to ValueMetaGraph #4031
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/core/value/ValueMetaGraph.java
  plugins/tech/neo4j/src/main/resources/graph.svg
Labels: Neo4j

#4037 fix some Java 17 things and disable flink, fixes #4036
  assemblies/lib/pom.xml
  assemblies/plugins/transforms/script/pom.xml
  assemblies/plugins/transforms/script/src/assembly/assembly.xml
  assemblies/static/src/main/resources/config/projects/samples/metadata/pipeline-run-configuration/local.json
  assemblies/static/src/main/resources/config/projects/samples/metadata/workflow-run-configuration/local.json
  assemblies/static/src/main/resources/config/projects/samples/project-config.json
  assemblies/static/src/main/resources/hop-conf.bat
  assemblies/static/src/main/resources/hop-conf.sh
  assemblies/static/src/main/resources/hop-encrypt.bat
  assemblies/static/src/main/resources/hop-encrypt.sh
  assemblies/static/src/main/resources/hop-gui.bat
  assemblies/static/src/main/resources/hop-gui.sh
  assemblies/static/src/main/resources/hop-import.bat
  assemblies/static/src/main/resources/hop-import.sh
  assemblies/static/src/main/resources/hop-run.bat
  assemblies/static/src/main/resources/hop-run.sh
  assemblies/static/src/main/resources/hop-search.bat
  assemblies/static/src/main/resources/hop-search.sh
  assemblies/static/src/main/resources/hop-server.bat
  assemblies/static/src/main/resources/hop-server.sh
  assemblies/static/src/main/resources/hop-translator.bat
  assemblies/static/src/main/resources/hop-translator.sh
  docker/integration-tests/Dockerfile.unit-tests
  docker/integration-tests/integration-tests-flink.yaml
  integration-tests/flink/disabled.txt
  integration-tests/spreadsheet/files/sample-file-append.xlsx
  plugins/transforms/script/src/main/java/org/apache/hop/pipeline/transforms/script/ScriptUtils.java
Labels: Containers, Integration Testing

#4039 add nashorn installation steps to Script transform docs. fixes #4038
  docs/hop-user-manual/modules/ROOT/pages/hop-gui/shortcuts.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/script.adoc
Labels: Documentation

#4048 Fix #3686 - CLI commands on Windows when folder variables contain spaces
  assemblies/static/src/main/resources/hop-conf.bat
  assemblies/static/src/main/resources/hop-encrypt.bat
  assemblies/static/src/main/resources/hop-gui.bat
  assemblies/static/src/main/resources/hop-import.bat
  assemblies/static/src/main/resources/hop-run.bat
  assemblies/static/src/main/resources/hop-search.bat
  assemblies/static/src/main/resources/hop-server.bat
  assemblies/static/src/main/resources/hop-translator.bat
Labels: CLI

#4051 updated Stream Schema Merge transform documentation. #4049
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/streamschemamerge.adoc
Labels: Documentation

#4041 Translations update from Weblate
  engine/src/main/resources/org/apache/hop/execution/sampler/plugins/dataprof/messages/messages_pt_BR.properties
  plugins/actions/as400command/src/main/resources/org/apache/hop/workflow/actions/as400command/messages/messages_pt_BR.properties
  plugins/actions/mailvalidator/src/main/resources/org/apache/hop/workflow/actions/mailvalidator/messages/messages_pt_BR.properties
  plugins/actions/tableexists/src/main/resources/org/apache/hop/workflow/actions/tableexists/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/engines/spark/messages/messages_pt_BR.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/pubsub/messages/messages_pt_BR.properties
  plugins/misc/static-schema/src/main/resources/org/apache/hop/staticschema/metadata/messages/messages_pt_BR.properties
  plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/config/messages/messages_pt_BR.properties
  plugins/transforms/analyticquery/src/main/resources/org/apache/hop/pipeline/transforms/analyticquery/messages/messages_pt_BR.properties
  plugins/transforms/append/src/main/resources/org/apache/hop/pipeline/transforms/append/messages/messages_pt_BR.properties
  plugins/transforms/blockuntiltransformsfinish/src/main/resources/org/apache/hop/pipeline/transforms/blockuntiltransformsfinish/messages/messages_pt_BR.properties
  plugins/transforms/delay/src/main/resources/org/apache/hop/pipeline/transforms/delay/messages/messages_pt_BR.properties
  plugins/transforms/excel/src/main/resources/org/apache/hop/pipeline/transforms/excelwriter/messages/messages_pt_BR.properties
  plugins/transforms/mapping/src/main/resources/org/apache/hop/pipeline/transforms/input/messages/messages_pt_BR.properties
  plugins/transforms/salesforce/src/main/resources/org/apache/hop/pipeline/transforms/salesforceinput/messages/messages_pt_BR.properties
  plugins/transforms/streamschemamerge/src/main/resources/org/apache/hop/pipeline/transforms/streamschemamerge/messages/messages_pt_BR.properties
  plugins/transforms/tablecompare/src/main/resources/org/apache/hop/pipeline/transforms/tablecompare/messages/messages_pt_BR.properties
  plugins/transforms/xml/src/main/resources/org/apache/hop/pipeline/transforms/xml/addxml/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/execution/profiling/messages/messages_pt_BR.properties
Labels: Hop Gui

#4047 Fix #4025 - Update calculator.adoc (#1)
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/calculator.adoc
Labels: Documentation

#4034 Fix Delete transform (Metadata injection) #4015
  plugins/transforms/delete/src/main/java/org/apache/hop/pipeline/transforms/delete/DeleteKeyField.java
  plugins/transforms/delete/src/main/java/org/apache/hop/pipeline/transforms/delete/DeleteLookupField.java
  plugins/transforms/delete/src/main/java/org/apache/hop/pipeline/transforms/delete/DeleteMeta.java
  plugins/transforms/delete/src/main/resources/org/apache/hop/pipeline/transforms/delete/messages/messages_de_DE.properties
  plugins/transforms/delete/src/main/resources/org/apache/hop/pipeline/transforms/delete/messages/messages_en_US.properties
  plugins/transforms/delete/src/main/resources/org/apache/hop/pipeline/transforms/delete/messages/messages_pt_BR.properties
  plugins/transforms/delete/src/main/resources/org/apache/hop/pipeline/transforms/delete/messages/messages_zh_CN.properties
Labels: Transforms

#4080 HopGuiFileDefaultFolder create wrong path on Windows #4073
  plugins/misc/projects/src/main/java/org/apache/hop/projects/xp/HopGuiFileDefaultFolder.java
  ui/src/main/java/org/apache/hop/ui/hopgui/perspective/execution/PipelineExecutionViewer.java
Labels: Hop Gui

#4089 updated database documentation and minor updates. fixes #3548
  docs/hop-user-manual/modules/ROOT/pages/database/databases.adoc
  docs/hop-user-manual/modules/ROOT/pages/database/databases/oracle.adoc
Labels: Documentation
