Repository apache/hop, pull requests merged in 2024-08, with the labels that each got.

#4188 move SWT to compile so plugins don't need to add it, fixes #4187
  engine-beam/pom.xml
  plugins/engines/beam/src/assembly/assembly.xml
  ui/pom.xml
  ui/src/assembly/assembly.xml
Labels: Beam, Hop Gui

#4199 [SONAR] cleanup
  core/src/main/java/org/apache/hop/core/Result.java
  engine/src/main/java/org/apache/hop/pipeline/transforms/file/BaseFileInputTransformData.java
  engine/src/main/java/org/apache/hop/workflow/WorkflowPainterExtension.java
  plugins/actions/copyfiles/src/main/java/org/apache/hop/workflow/actions/copyfiles/ActionCopyFiles.java
  plugins/actions/deletefolders/src/main/java/org/apache/hop/workflow/actions/deletefolders/ActionDeleteFolders.java
  plugins/actions/dostounix/src/main/java/org/apache/hop/workflow/actions/dostounix/ActionDosToUnix.java
  plugins/actions/evalfilesmetrics/src/main/java/org/apache/hop/workflow/actions/evalfilesmetrics/ActionEvalFilesMetrics.java
  plugins/actions/ftp/src/main/java/org/apache/hop/workflow/actions/ftp/ActionFtp.java
  plugins/actions/getpop/src/main/java/org/apache/hop/workflow/actions/getpop/ActionGetPOP.java
  plugins/actions/movefiles/src/main/java/org/apache/hop/workflow/actions/movefiles/ActionMoveFiles.java
  plugins/actions/pgpfiles/src/main/java/org/apache/hop/workflow/actions/pgpdecryptfiles/ActionPGPDecryptFiles.java
  plugins/actions/pgpfiles/src/main/java/org/apache/hop/workflow/actions/pgpencryptfiles/ActionPGPEncryptFiles.java
  plugins/actions/ping/src/main/java/org/apache/hop/workflow/actions/ping/ActionPing.java
  plugins/actions/shell/src/main/java/org/apache/hop/workflow/actions/shell/ActionShell.java
  plugins/actions/unzip/src/main/java/org/apache/hop/workflow/actions/unzip/ActionUnZip.java
  plugins/tech/avro/src/main/java/org/apache/hop/avro/transforms/avrooutput/AvroOutputData.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sns/SnsNotifyData.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReaderData.java
  plugins/tech/azure/src/main/java/org/apache/hop/pipeline/transforms/eventhubs/listen/AzureListenerData.java
  plugins/tech/azure/src/main/java/org/apache/hop/pipeline/transforms/eventhubs/write/AzureWriterData.java
  plugins/tech/cassandra/src/main/java/org/apache/hop/pipeline/transforms/cassandrainput/CassandraInputData.java
  plugins/tech/cassandra/src/main/java/org/apache/hop/pipeline/transforms/cassandraoutput/CassandraOutputData.java
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsInputData.java
  plugins/tech/google/src/main/java/org/apache/hop/pipeline/transforms/googlesheets/GoogleSheetsOutputData.java
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/cypher/CypherData.java
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/cypherbuilder/CypherBuilderData.java
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/gencsv/GenerateCsvData.java
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/graph/GraphOutput.java
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/graph/GraphOutputData.java
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/importer/ImporterData.java
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/output/Neo4JOutputData.java
  plugins/tech/neo4j/src/main/java/org/apache/hop/neo4j/transforms/split/SplitGraphData.java
  plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/input/ParquetInputData.java
  plugins/tech/parquet/src/main/java/org/apache/hop/parquet/transforms/output/ParquetOutputData.java
  plugins/transforms/calculator/src/main/java/org/apache/hop/pipeline/transforms/calculator/Calculator.java
  plugins/transforms/edi2xml/src/main/java/org/apache/hop/pipeline/transforms/edi2xml/grammar/FastSimpleGenericEdifactDirectXMLParser.java
  plugins/transforms/memgroupby/src/main/java/org/apache/hop/pipeline/transforms/memgroupby/Aggregate.java
  ui/src/main/java/org/apache/hop/ui/core/FileDialogOperation.java
  ui/src/main/java/org/apache/hop/ui/core/dialog/ActionDetails.java
  ui/src/main/java/org/apache/hop/ui/core/dialog/EnterPrintDialog.java
  ui/src/main/java/org/apache/hop/ui/hopgui/HopGui.java
  ui/src/main/java/org/apache/hop/ui/hopgui/file/pipeline/HopGuiPipelineGraph.java
  ui/src/main/java/org/apache/hop/ui/hopgui/file/shared/HopGuiTooltipExtension.java
  ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/HopGuiWorkflowGraph.java
  ui/src/main/java/org/apache/hop/ui/hopgui/file/workflow/delegates/HopGuiWorkflowClipboardExtension.java
  ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
Labels: Hop Gui, Neo4j

#4207 best practices updates. fixes #4204
  docs/hop-user-manual/modules/ROOT/pages/best-practices/index.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/governance.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/logging.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/loops.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/mappings.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/metadata-injection.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/naming-conventions.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/performance-basics.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/size-matters.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/best-practices/variables.adoc
Labels: Documentation

#4219 Translations update from Weblate
  plugins/actions/abort/src/main/resources/org/apache/hop/workflow/actions/abort/messages/messages_zh_CN.properties
  plugins/actions/addresultfilenames/src/main/resources/org/apache/hop/workflow/actions/addresultfilenames/messages/messages_zh_CN.properties
  plugins/actions/as400command/src/main/resources/org/apache/hop/workflow/actions/as400command/messages/messages_zh_CN.properties
  plugins/actions/checkdbconnection/src/main/resources/org/apache/hop/workflow/actions/checkdbconnection/messages/messages_zh_CN.properties
  plugins/actions/checkfilelocked/src/main/resources/org/apache/hop/workflow/actions/checkfilelocked/messages/messages_zh_CN.properties
  plugins/actions/columnsexist/src/main/resources/org/apache/hop/workflow/actions/columnsexist/messages/messages_zh_CN.properties
  plugins/databases/access/src/main/resources/org/apache/hop/pipeline/transforms/accessoutput/messages/messages_zh_CN.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/bigtable/messages/messages_zh_CN.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/transforms/bq/messages/messages_zh_CN.properties
  plugins/misc/async/src/main/resources/org/apache/hop/www/async/messages/messages_zh_CN.properties
  plugins/misc/debug/src/main/resources/org/apache/hop/debug/action/messages/messages_zh_CN.properties
  plugins/tech/avro/src/main/resources/org/apache/hop/avro/transforms/avrodecode/messages/messages_zh_CN.properties
  plugins/tech/avro/src/main/resources/org/apache/hop/avro/transforms/avroencode/messages/messages_zh_CN.properties
  plugins/tech/avro/src/main/resources/org/apache/hop/avro/transforms/avroinput/messages/messages_zh_CN.properties
  plugins/tech/avro/src/main/resources/org/apache/hop/avro/transforms/avrooutput/messages/messages_zh_CN.properties
  plugins/tech/aws/src/main/resources/org/apache/hop/pipeline/transforms/redshift/bulkloader/messages/messages_zh_CN.properties
  plugins/tech/cassandra/src/main/resources/org/apache/hop/pipeline/transforms/cassandrainput/messages/messages_zh_CN.properties
  plugins/tech/cassandra/src/main/resources/org/apache/hop/pipeline/transforms/cassandraoutput/messages/messages_zh_CN.properties
  plugins/tech/cassandra/src/main/resources/org/apache/hop/pipeline/transforms/cassandrasstableoutput/messages/messages_zh_CN.properties
  plugins/tech/neo4j/src/main/resources/org/apache/hop/neo4j/actions/check/messages/messages_zh_CN.properties
  plugins/transforms/abort/src/main/resources/org/apache/hop/pipeline/transforms/abort/messages/messages_zh_CN.properties
  plugins/transforms/addsequence/src/main/resources/org/apache/hop/pipeline/transforms/addsequence/messages/messages_zh_CN.properties
  plugins/transforms/analyticquery/src/main/resources/org/apache/hop/pipeline/transforms/analyticquery/messages/messages_zh_CN.properties
  plugins/transforms/append/src/main/resources/org/apache/hop/pipeline/transforms/append/messages/messages_zh_CN.properties
  plugins/transforms/blockingtransform/src/main/resources/org/apache/hop/pipeline/transforms/blockingtransform/messages/messages_zh_CN.properties
  plugins/transforms/blockuntiltransformsfinish/src/main/resources/org/apache/hop/pipeline/transforms/blockuntiltransformsfinish/messages/messages_zh_CN.properties
  plugins/transforms/calculator/src/main/resources/org/apache/hop/pipeline/transforms/calculator/messages/messages_zh_CN.properties
  plugins/transforms/changefileencoding/src/main/resources/org/apache/hop/pipeline/transforms/changefileencoding/messages/messages_zh_CN.properties
  plugins/transforms/checksum/src/main/resources/org/apache/hop/pipeline/transforms/checksum/messages/messages_zh_CN.properties
  plugins/transforms/clonerow/src/main/resources/org/apache/hop/pipeline/transforms/clonerow/messages/messages_zh_CN.properties
  plugins/transforms/closure/src/main/resources/org/apache/hop/pipeline/transforms/closure/messages/messages_zh_CN.properties
  plugins/transforms/coalesce/src/main/resources/org/apache/hop/pipeline/transforms/coalesce/messages/messages_zh_CN.properties
  plugins/transforms/columnexists/src/main/resources/org/apache/hop/pipeline/transforms/columnexists/messages/messages_zh_CN.properties
  plugins/transforms/combinationlookup/src/main/resources/org/apache/hop/pipeline/transforms/combinationlookup/messages/messages_zh_CN.properties
  plugins/transforms/snowflake/src/main/resources/org/apache/hop/pipeline/transforms/snowflake/bulkloader/messages/messages_zh_CN.properties
  plugins/transforms/tokenreplacement/src/main/resources/org/apache/hop/pipeline/transforms/tokenreplacement/messages/messages_zh_CN.properties
  plugins/transforms/verticabulkloader/src/main/resources/org/apache/hop/pipeline/transforms/vertica/bulkloader/messages/messages_zh_CN.properties
  plugins/transforms/xml/src/main/resources/org/apache/hop/pipeline/transforms/xml/addxml/messages/messages_zh_CN.properties
  ui/src/main/resources/org/apache/hop/ui/core/auth/messages/messages_zh_CN.properties
  ui/src/main/resources/org/apache/hop/ui/pipeline/transform/common/messages/messages_zh_CN.properties
  ui/src/main/resources/org/apache/hop/ui/workflow/actions/messages/messages_zh_CN.properties
Labels: Hop Gui, Neo4j

#4217 Update Documentation:internationalisation.adoc
  docs/hop-dev-manual/modules/ROOT/pages/internationalisation.adoc
Labels: Documentation

#4222 Translations update from Weblate
  engine/src/main/resources/org/apache/hop/core/auth/core/messages/messages_zh_CN.properties
  plugins/actions/copyfiles/src/main/resources/org/apache/hop/workflow/actions/copyfiles/messages/messages_zh_CN.properties
  plugins/actions/copymoveresultfilenames/src/main/resources/org/apache/hop/workflow/actions/copymoveresultfilenames/messages/messages_zh_CN.properties
  plugins/misc/projects/src/main/resources/org/apache/hop/projects/config/messages/messages_zh_CN.properties
  plugins/tech/azure/src/main/resources/org/apache/hop/vfs/azure/config/messages/messages_zh_CN.properties
  plugins/tech/google/src/main/resources/org/apache/hop/vfs/googledrive/config/messages/messages_zh_CN.properties
  plugins/tech/google/src/main/resources/org/apache/hop/vfs/gs/config/messages/messages_zh_CN.properties
  plugins/transforms/concatfields/src/main/resources/org/apache/hop/pipeline/transforms/concatfields/messages/messages_zh_CN.properties
  plugins/transforms/constant/src/main/resources/org/apache/hop/pipeline/transforms/constant/messages/messages_zh_CN.properties
  plugins/transforms/kafka/src/main/resources/org/apache/hop/pipeline/transforms/kafka/consumer/messages/messages_zh_CN.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/configuration/messages/messages_zh_CN.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/explorer/config/messages/messages_zh_CN.properties
  ui/src/main/resources/org/apache/hop/ui/pipeline/config/messages/messages_zh_CN.properties
  ui/src/main/resources/org/apache/hop/ui/workflow/config/messages/messages_zh_CN.properties
Labels: Hop Gui

#4236 Add doc for Oracle connection with TNS_ADMIN #4225
  docs/hop-user-manual/modules/ROOT/pages/database/databases/oracle.adoc
Labels: Documentation

#4239 Add option to block execution of specific code. fixes #4238
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/userdefinedjavaclass.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/userdefinedjavaexpression.adoc
  plugins/transforms/janino/src/assembly/assembly.xml
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/Janino.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/JaninoDialog.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/janino/JaninoMeta.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/javafilter/JavaFilter.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/FieldHelper.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/TransformDefinition.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClass.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassDef.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassDialog.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassMeta.java
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/util/JaninoCheckerUtil.java
  plugins/transforms/janino/src/main/resources/codeExclusions.xml
  plugins/transforms/janino/src/test/java/org/apache/hop/pipeline/transforms/userdefinedjavaclass/UserDefinedJavaClassMetaTest.java
Labels: Documentation

#4214 Fix http authentication with proxy
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/rest.adoc
  plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java
Labels: Documentation

#4243 fix: add missing volume mounts to docker-compose.yaml
  docs/hop-user-manual/modules/ROOT/assets/files/how-to-guides/apache-airflow/docker-compose.yaml
Labels: Documentation

#4260 Cannot save web service when editing run configuration #4258
  plugins/misc/async/src/main/java/org/apache/hop/www/async/AsyncWebServiceEditor.java
  ui/src/main/java/org/apache/hop/ui/core/widget/MetaSelectionLine.java
Labels: Hop Gui, Metadata
