Repository apache/hop, pull requests merged in 2024-02, with the labels that each got.

#3599 Fix HopServer charset decoding to UTF-8 #3590
  engine/src/main/java/org/apache/hop/server/HopServer.java
Labels: Hop Server

#3608 Record action execution duration #3606
  engine/src/main/java/org/apache/hop/workflow/Workflow.java
Labels: Workflows

#3613 Renaming a file in FileDialog is not readable on Windows in dark mode #3612
  ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
Labels: Hop Gui

#3615 File separator hard coded in HopVfsFileDialog #3614
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/workflow-logging.adoc
  ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
Labels: Documentation, Hop Gui

#3617 Add maximize button to HopVfsDialog #3616
  ui/src/main/java/org/apache/hop/ui/core/vfs/HopVfsFileDialog.java
Labels: Hop Gui

#3595 Upgrade Rhino from 1.7.12 to 1.7.14 #3586
  pom.xml
Labels: dependencies

#3596 Transform "Generate random value" throw NPE if no input row #3592
  plugins/transforms/randomvalue/src/main/java/org/apache/hop/pipeline/transforms/randomvalue/RandomValue.java
  plugins/transforms/stringoperations/src/main/java/org/apache/hop/pipeline/transforms/stringoperations/StringOperations.java
Labels: Transforms

#3625 Fix delete folder through File Explorer #3620
  ui/src/main/java/org/apache/hop/ui/hopgui/perspective/explorer/ExplorerPerspective.java
  ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/explorer/messages/messages_en_US.properties
Labels: Hop Gui

#3611 Replaces "UTF-8" strings with StandardCharsets.UTF_8 #3610
  core/src/main/java/org/apache/hop/core/plugins/BasePluginType.java
  core/src/main/java/org/apache/hop/core/plugins/PluginRegistry.java
  core/src/main/java/org/apache/hop/core/variables/VariableRegistry.java
  engine/src/main/java/org/apache/hop/pipeline/engines/remote/RemotePipelineEngine.java
  engine/src/main/java/org/apache/hop/resource/ResourceUtil.java
  engine/src/main/java/org/apache/hop/server/HopServer.java
  engine/src/main/java/org/apache/hop/www/GetPipelineImageServlet.java
  engine/src/main/java/org/apache/hop/www/GetPipelineStatusServlet.java
  engine/src/main/java/org/apache/hop/www/GetWorkflowImageServlet.java
  engine/src/main/java/org/apache/hop/www/GetWorkflowStatusServlet.java
  engine/src/main/java/org/apache/hop/www/PausePipelineServlet.java
  engine/src/main/java/org/apache/hop/www/PrepareExecutionPipelineServlet.java
  engine/src/main/java/org/apache/hop/www/SniffTransformServlet.java
  engine/src/main/java/org/apache/hop/www/StartExecutionPipelineServlet.java
  engine/src/main/java/org/apache/hop/www/StartPipelineServlet.java
  engine/src/main/java/org/apache/hop/www/StartWorkflowServlet.java
  engine/src/main/java/org/apache/hop/www/StopPipelineServlet.java
  engine/src/main/java/org/apache/hop/www/StopWorkflowServlet.java
  engine/src/test/java/org/apache/hop/core/util/ConfigurableStreamLoggerTest.java
  engine/src/test/java/org/apache/hop/utils/TestUtils.java
Labels: task

#3632 Write to log action set default to a Basic log level #3629
  plugins/actions/writetolog/src/main/java/org/apache/hop/workflow/actions/writetolog/ActionWriteToLog.java
Labels: Actions

#3638 Changed jandex version from 3.0.5 to 3.1.6
  docs/hop-dev-manual/modules/ROOT/pages/porting-kettle-plugins.adoc
  pom.xml
Labels: Documentation

#3641 Fix for issues #3618, #2498, #2006, #1956
  engine/src/test/java/org/apache/hop/workflow/action/ActionSerializationTestUtil.java
  integration-tests/actions/0008-zip-action-archive-files.hwf
  integration-tests/actions/main-0008-zip-files.hwf
  plugins/actions/checkfilelocked/src/main/java/org/apache/hop/workflow/actions/checkfilelocked/ActionCheckFilesLocked.java
  plugins/actions/checkfilelocked/src/main/java/org/apache/hop/workflow/actions/checkfilelocked/ActionCheckFilesLockedDialog.java
  plugins/actions/checkfilelocked/src/test/java/org/apache/hop/workflow/actions/checkfilelocked/ActionCheckFilesLockedTest.java
  plugins/actions/checkfilelocked/src/test/java/org/apache/hop/workflow/actions/checkfilelocked/WorkflowActionCheckFilesLockedLoadSaveTest.java
  plugins/actions/checkfilelocked/src/test/resources/check-files-locked-action.xml
  plugins/actions/zipfile/src/main/java/org/apache/hop/workflow/actions/zipfile/ActionZipFile.java
  plugins/actions/zipfile/src/main/java/org/apache/hop/workflow/actions/zipfile/ActionZipFileDialog.java
  plugins/actions/zipfile/src/test/java/org/apache/hop/workflow/actions/zipfile/ActioZipFileTest.java
  plugins/actions/zipfile/src/test/java/org/apache/hop/workflow/actions/zipfile/WorkflowActionZipFileLoadSaveTest.java
  plugins/actions/zipfile/src/test/resources/zip-files-action.xml
Labels: Integration Testing

#3645 [Feature 36936] Updated documentation to warn the user about mixing meta types in row…
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/rownormaliser.adoc
Labels: Documentation

#3600 Fix InitCap in String Operation to convert the rest of each word to lower case #3538
  core/src/main/java/org/apache/hop/core/row/ValueDataUtil.java
Labels: Transforms

#3635 Update tableinput.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/tableinput.adoc
Labels: Documentation

#3648 Update tableinput.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/tableinput.adoc
Labels: Documentation

#3649 Java filter: Fix to make destinations optional #3136
  plugins/transforms/janino/src/main/java/org/apache/hop/pipeline/transforms/javafilter/JavaFilter.java
Labels: Transforms

#3663 AWS SNS Notify transform initial version. #3601
  assemblies/plugins/tech/aws/pom.xml
  assemblies/plugins/tech/aws/src/assembly/assembly.xml
  docs/hop-user-manual/modules/ROOT/assets/images/transforms/icons/aws-sns.svg
  docs/hop-user-manual/modules/ROOT/nav.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/aws-sns-notify.adoc
  plugins/tech/aws/pom.xml
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sns/AwsSns.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sns/SnsNotify.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sns/SnsNotifyData.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sns/SnsNotifyDialog.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sns/SnsNotifyMeta.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/AwsSqsReader.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReader.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReaderData.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReaderDialog.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReaderMeta.java
  plugins/tech/aws/src/main/resources/aws-sns.svg
  plugins/tech/aws/src/main/resources/aws-sqs.svg
  plugins/tech/aws/src/main/resources/org/apache/hop/pipeline/transforms/aws/sns/messages/messages_en_US.properties
  plugins/tech/aws/src/main/resources/org/apache/hop/pipeline/transforms/aws/sqs/messages/messages_en_US.properties
Labels: Documentation

#3664 fix #3510, fix #3512, fix #3665
  core/src/main/java/org/apache/hop/core/database/BaseDatabaseMeta.java
  core/src/main/java/org/apache/hop/core/database/IDatabase.java
  core/src/main/java/org/apache/hop/core/row/value/ValueMetaBase.java
  core/src/test/java/org/apache/hop/core/row/value/ValueMetaBaseSetPreparedStmntValueTest.java
  docs/hop-user-manual/modules/ROOT/pages/database/databases/duckdb.adoc
  plugins/databases/duckdb/src/main/java/org/apache/hop/databases/duckdb/DuckDBDatabaseMeta.java
  plugins/transforms/tableoutput/src/main/java/org/apache/hop/pipeline/transforms/tableoutput/TableOutput.java
Labels: Documentation

#3667 AWS SQS Reader initial version. #3602
  docs/hop-user-manual/modules/ROOT/assets/images/transforms/icons/aws-sqs.svg
  docs/hop-user-manual/modules/ROOT/nav.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms.adoc
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/aws-sqs-reader.adoc
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReader.java
  plugins/tech/aws/src/main/java/org/apache/hop/pipeline/transforms/aws/sqs/SqsReaderMeta.java
Labels: Documentation

#3688 Translations update from Weblate
  plugins/actions/checkdbconnection/src/main/resources/org/apache/hop/workflow/actions/checkdbconnection/messages/messages_de_DE.properties
  plugins/actions/columnsexist/src/main/resources/org/apache/hop/workflow/actions/columnsexist/messages/messages_de_DE.properties
  plugins/actions/evaluatetablecontent/src/main/resources/org/apache/hop/workflow/actions/evaluatetablecontent/messages/messages_de_DE.properties
  plugins/actions/getpop/src/main/resources/org/apache/hop/workflow/actions/getpop/messages/messages_pt_BR.properties
  plugins/actions/waitforsql/src/main/resources/org/apache/hop/workflow/actions/waitforsql/messages/messages_de_DE.properties
  plugins/engines/beam/src/main/resources/org/apache/hop/beam/metadata/messages/messages_pt_BR.properties
  plugins/tech/avro/src/main/resources/org/apache/hop/avro/transforms/avrodecode/messages/messages_de_DE.properties
  plugins/tech/google/src/main/resources/org/apache/hop/pipeline/transforms/googlesheets/messages/messages_pt_BR.properties
  plugins/transforms/calculator/src/main/resources/org/apache/hop/pipeline/transforms/calculator/messages/messages_de_DE.properties
  plugins/transforms/checksum/src/main/resources/org/apache/hop/pipeline/transforms/checksum/messages/messages_pt_BR.properties
  plugins/transforms/detectlastrow/src/main/resources/org/apache/hop/pipeline/transforms/detectlastrow/messages/messages_de_DE.properties
  plugins/transforms/excel/src/main/resources/org/apache/hop/pipeline/transforms/excelinput/messages/messages_de_DE.properties
  plugins/transforms/fieldschangesequence/src/main/resources/org/apache/hop/pipeline/transforms/fieldschangesequence/messages/messages_pt_BR.properties
  plugins/transforms/filesfromresult/src/main/resources/org/apache/hop/pipeline/transforms/filesfromresult/messages/messages_de_DE.properties
  plugins/transforms/filestoresult/src/main/resources/org/apache/hop/pipeline/transforms/filestoresult/messages/messages_de_DE.properties
  plugins/transforms/filterrows/src/main/resources/org/apache/hop/pipeline/transforms/filterrows/messages/messages_de_DE.properties
  plugins/transforms/formula/src/main/resources/org/apache/hop/pipeline/transforms/formula/messages/messages_de_DE.properties
  plugins/transforms/formula/src/main/resources/org/apache/hop/pipeline/transforms/formula/messages/messages_pt_BR.properties
  plugins/transforms/getfilenames/src/main/resources/org/apache/hop/pipeline/transforms/getfilenames/messages/messages_pt_BR.properties
  plugins/transforms/groupby/src/main/resources/org/apache/hop/pipeline/transforms/groupby/messages/messages_pt_BR.properties
  plugins/transforms/ifnull/src/main/resources/org/apache/hop/pipeline/transforms/ifnull/messages/messages_pt_BR.properties
  plugins/transforms/janino/src/main/resources/org/apache/hop/pipeline/transforms/janino/messages/messages_pt_BR.properties
  plugins/transforms/joinrows/src/main/resources/org/apache/hop/pipeline/transforms/joinrows/messages/messages_pt_BR.properties
  plugins/transforms/mailinput/src/main/resources/org/apache/hop/pipeline/transforms/mailinput/messages/messages_pt_BR.properties
  plugins/transforms/mongodb/src/main/resources/org/apache/hop/pipeline/transforms/mongodbdelete/messages/messages_pt_BR.properties
  plugins/transforms/mongodb/src/main/resources/org/apache/hop/pipeline/transforms/mongodbinput/messages/messages_pt_BR.properties
  plugins/transforms/mongodb/src/main/resources/org/apache/hop/pipeline/transforms/mongodboutput/messages/messages_pt_BR.properties
  plugins/transforms/propertyinput/src/main/resources/org/apache/hop/pipeline/transforms/propertyinput/messages/messages_pt_BR.properties
  plugins/transforms/setvalueconstant/src/main/resources/org/apache/hop/pipeline/transforms/setvalueconstant/messages/messages_pt_BR.properties
  plugins/transforms/sort/src/main/resources/org/apache/hop/pipeline/transforms/sort/messages/messages_pt_BR.properties
  plugins/transforms/tableinput/src/main/resources/org/apache/hop/pipeline/transforms/tableinput/messages/messages_de_DE.properties
  plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/csvinput/messages/messages_de_DE.properties
  plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/fileinput/messages/messages_de_DE.properties
  plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/fileinput/text/messages/messages_de_DE.properties
  plugins/transforms/writetolog/src/main/resources/org/apache/hop/pipeline/transforms/writetolog/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/core/dialog/messages/messages_de_DE.properties
  ui/src/main/resources/org/apache/hop/ui/core/widget/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/messages/messages_de_DE.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/execution/messages/messages_de_DE.properties
  ui/src/main/resources/org/apache/hop/ui/hopgui/perspective/metadata/messages/messages_pt_BR.properties
  ui/src/main/resources/org/apache/hop/ui/pipeline/dialog/messages/messages_de_DE.properties
Labels: Hop Gui
