Repository apache/hop, pull requests merged in 2025-01, with the labels that each got.

#4746 #4612 and #4645
  assemblies/plugins/pom.xml
  lib-jdbc/pom.xml
  plugins/databases/as400/pom.xml
  plugins/databases/as400/src/assembly/assembly.xml
Labels: Database

#4760 disable assemblies and test during release, fixes #4759
  docs/hop-dev-manual/modules/ROOT/pages/apache-release/creating-a-release.adoc
  pom.xml
Labels: Documentation

#4792 salesforce input - added delete example case.fixes #4481
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/salesforceinput.adoc
Labels: Documentation

#4783 allow setting a rounding mode when writing a textfile, fixes #4782
  core/src/main/java/org/apache/hop/core/row/IValueMeta.java
  core/src/main/java/org/apache/hop/core/row/ValueMetaDeserializer.java
  core/src/main/java/org/apache/hop/core/row/value/ValueMetaBase.java
  core/src/main/java/org/apache/hop/core/row/value/ValueMetaFactory.java
  core/src/main/resources/org/apache/hop/core/messages/messages_en_US.properties
  docs/hop-user-manual/modules/ROOT/pages/pipeline/transforms/textfileoutput.adoc
  docs/hop-user-manual/modules/ROOT/pages/snippets/rounding-types.adoc
  plugins/misc/static-schema/src/main/java/org/apache/hop/staticschema/metadata/SchemaDefinitionEditor.java
  plugins/misc/static-schema/src/main/java/org/apache/hop/staticschema/metadata/SchemaFieldDefinition.java
  plugins/misc/static-schema/src/main/resources/org/apache/hop/staticschema/metadata/messages/messages_en_US.properties
  plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/textfileoutput/TextFileField.java
  plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/textfileoutput/TextFileOutputDialog.java
  plugins/transforms/textfile/src/main/java/org/apache/hop/pipeline/transforms/textfileoutput/TextFileOutputMeta.java
  plugins/transforms/textfile/src/main/resources/org/apache/hop/pipeline/transforms/textfileoutput/messages/messages_en_US.properties
  plugins/transforms/textfile/src/test/java/org/apache/hop/pipeline/transforms/textfileoutput/TextFileOutputMetaTest.java
  plugins/transforms/textfile/src/test/java/org/apache/hop/pipeline/transforms/textfileoutput/TextFileOutputTest.java
Labels: Documentation

#4798 Implementing issue #3978 (Caching File Execution Information Location)
  docs/hop-user-manual/modules/ROOT/pages/metadata-types/execution-information-location.adoc
  engine/src/main/java/org/apache/hop/execution/Execution.java
  engine/src/main/java/org/apache/hop/execution/ExecutionBuilder.java
  engine/src/main/java/org/apache/hop/execution/ExecutionData.java
  engine/src/main/java/org/apache/hop/execution/ExecutionState.java
  engine/src/main/java/org/apache/hop/execution/caching/CacheEntry.java
  engine/src/main/java/org/apache/hop/execution/caching/CachingFileExecutionInfoLocation.java
  engine/src/main/resources/org/apache/hop/execution/caching/messages/messages_en_US.properties
Labels: Documentation

#4797 rest metadata type and client fixes #4369
  integration-tests/http/0017-rest-metadata-type.hpl
  integration-tests/http/main-0017-rest-metadata-type.hwf
  integration-tests/http/metadata/restconnection/castlemock.json
  plugins/misc/rest/src/main/java/org/apache/hop/metadata/rest/RestConnection.java
  plugins/misc/rest/src/main/java/org/apache/hop/metadata/rest/RestConnectionEditor.java
  plugins/misc/rest/src/test/java/org/apache/hop/metadata/rest/RestTest.java
  plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/Rest.java
  plugins/transforms/rest/src/main/java/org/apache/hop/pipeline/transforms/rest/RestDialog.java
Labels: Integration Testing

#4816 AsyncWebService help button doesn't work #4815
  docs/hop-user-manual/modules/ROOT/nav.adoc
  docs/hop-user-manual/modules/ROOT/pages/hop-server/async-web-service.adoc
  docs/hop-user-manual/modules/ROOT/pages/metadata-types/async-web-service.adoc
  plugins/engines/beam/src/main/java/org/apache/hop/beam/metadata/JobParameter.java
  plugins/misc/async/src/main/java/org/apache/hop/www/async/AsyncWebService.java
  plugins/misc/async/src/main/resources/org/apache/hop/www/async/messages/messages_de_DE.properties
  plugins/misc/async/src/main/resources/org/apache/hop/www/async/messages/messages_en_US.properties
  plugins/misc/async/src/main/resources/org/apache/hop/www/async/messages/messages_fr_FR.properties
Labels: Documentation

#4828 Unresolved i18n title when opening metadata in a dialog window #4767
  ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataEditor.java
  ui/src/main/java/org/apache/hop/ui/core/metadata/MetadataManager.java
Labels: Hop Gui

#4840 use databaseMeta.getReservedWords() and fix variable resolver images/url
  core/src/main/java/org/apache/hop/core/variables/resolver/VariableResolver.java
  docs/hop-user-manual/modules/ROOT/pages/metadata-types/variable-resolver/pipeline-variable-resolver.adoc
  plugins/actions/sql/src/main/java/org/apache/hop/workflow/actions/sql/ActionSqlDialog.java
  plugins/actions/waitforsql/src/main/java/org/apache/hop/workflow/actions/waitforsql/ActionWaitForSqlDialog.java
  plugins/transforms/databasejoin/src/main/java/org/apache/hop/pipeline/transforms/databasejoin/DatabaseJoinDialog.java
  plugins/transforms/dynamicsqlrow/src/main/java/org/apache/hop/pipeline/transforms/dynamicsqlrow/DynamicSqlRowDialog.java
  plugins/transforms/sql/src/main/java/org/apache/hop/pipeline/transforms/sql/ExecSqlDialog.java
  plugins/transforms/tableinput/src/main/java/org/apache/hop/pipeline/transforms/tableinput/TableInputDialog.java
Labels: Documentation

#4851 minor fixes to concatfield - #4818, write to log fix #4850, proxy fix for http action #4768
  integration-tests/transforms/0004-concat-fields.hpl
  plugins/actions/http/src/main/java/org/apache/hop/workflow/actions/http/ActionHttp.java
  plugins/transforms/concatfields/src/main/java/org/apache/hop/pipeline/transforms/concatfields/ConcatField.java
  plugins/transforms/concatfields/src/main/java/org/apache/hop/pipeline/transforms/concatfields/ConcatFields.java
  plugins/transforms/concatfields/src/main/java/org/apache/hop/pipeline/transforms/concatfields/ConcatFieldsMeta.java
  plugins/transforms/concatfields/src/main/java/org/apache/hop/pipeline/transforms/concatfields/ExtraFields.java
  plugins/transforms/concatfields/src/test/java/org/apache/hop/pipeline/transforms/concatfields/ConcatFieldsMetaTest.java
  plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/LogField.java
  plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLogDialog.java
  plugins/transforms/writetolog/src/main/java/org/apache/hop/pipeline/transforms/writetolog/WriteToLogMeta.java
Labels: Integration Testing
